# Generated by Django 3.1 on 2020-08-17 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='friend_name',
            new_name='friendly_name',
        ),
    ]
